config/routes.rb
Rails.application.routes.draw do
  root 'users#login'
  get 'articles', to: 'articles#index'
  resources :articles
  resources :sessions
  get 'login', to: 'users#login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: {minimum: 6, maximum: 125}
  validates :description, presence: true, length: {minimum: 6, maximum: 200}

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: {casesensitive: false}, presence: true, length: {minimum: 6, maximum: 25}
  has_many :articles, dependent: :destroy
  has_secure_password

  def full_name
    return first_name + " " + last_name if first_name || last_name

    "Anonymous"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :requires_user
  helper_method :logged_in?

  private

  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end

  def logged_in?
    !!current_user
  end

  def requires_user
    if !logged_in?
      flash[:alert] = "You must sign in to perform that action"
      redirect_to :root
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :get_article, only:[:show, :destroy, :edit, :update]
  before_action :get_article_params, only:[:create, :update]
  before_action :requires_user

  def index
    @articles = current_user.articles
  end
  
  def show
  end

  def new
    @article = Article.new
  end

  def create
    #article_params = get_article_params
    article = Article.new
    article.title = @article_params[:title]
    article.description = @article_params[:description]
    article.user = current_user
    if article.save
      flash[:notice] = "New article created"
    else
      flash[:alert] = "Error creating article"
    end
    redirect_to :articles
  end

  def edit
  end

  def update
    @article.title = @article_params[:title]
    @article.description = @article_params[:description]
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article edited"
    else
      flash[:alert] = "Error editing article"
    end
    redirect_to :articles
  end

  def destroy
    flash[:notice] = "Article deleted"
    redirect_to :articles if @article.destroy
  end

  private

  def get_article
    @article = Article.find(params[:id])
  end

  def get_article_params
    @article_params = params.require(:article).permit(:title, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user_creds = get_user_creds
    user = User.find_by(username: user_creds[:username])
    if user && user.authenticate(user_creds[:password])
      session[:user_id] = user.id
      flash[:notice] = "You are signed in"
      redirect_to :articles
    else
      flash[:alert] = "Invalid credentials"
      redirect_to :login
    end
  end

  def destroy
    flash[:notice] = "You are signed out"
    session[:user_id] = nil
    redirect_to :root
  end

  private

  def get_user_creds
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def login
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_edit.html.erb
<%
  if @article.new_record?
    url = :articles
    method = :post
    heading_text = "New Article"
    action_button_text = "Create"
  else
    url = :article
    method = :patch
    heading_text = "Edit Article"
    action_button_text = "Edit"
  end
%>
<h1><%= heading_text %></h1>
<%= form_with(model: @article, url: url, method: method) do |f| %>
  <div class="form-group">
    <%= f.text_field :title, placeholder: "Enter title", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label "Description", :description %>
    <%= f.text_area :description, placeholder: "Enter description", class: "form-control", rows: "3" %>
  </div>
  <div class="form-group">
    <%= f.submit action_button_text, class: "btn btn-success" %>
    <%= link_to "Cancel", articles_path, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%= render "articles/edit" %>

app/views/articles/index.html.erb
<h1>Articles list</h1>
<% @articles.each do |article| %>
  <div class="card" class="shadow p-3 mb-5 bg-white rounded" style="width: 18rem;">
    <h5 class="card-header"><%= article.title %></h5>
    <div class="card-body">
      <h5 class="card-title">By <%= article.user.full_name %></h5>
      <p class="card-text"><p><%= article.description %></p>
      <p><strong>Created At:</strong>&nbsp;&nbsp;<%= time_ago_in_words(article.created_at) %></p>
      <p><strong>Updated At :</strong>&nbsp;&nbsp;<%= time_ago_in_words(article.created_at) %></p>
      <%= link_to "View", article_path(article), class:"btn btn-primary mr-2" %>
      <%= link_to "Edit", edit_article_path(article), class:"btn btn-success mr-2" %>
      <%= link_to "Delete", article_path(article), method: :delete, data: {confirm: 'Are you sure you want to delete?'},class: 'btn btn-danger' %>
    </div>
  </div>
<% end %>

app/views/articles/new.html.erb
<%= render "articles/edit" %>

app/views/articles/show.html.erb
<h1>Article details</h1>
<div>
  <div><strong>Title :</strong><%= @article.title %></div>
  <div><strong>Description :</strong><%= @article.description %></div>
</div>

<%= link_to "Home Page", articles_path %>

app/views/layouts/_messages.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success mt-5 mb-5" role="alert"><%= flash[:notice] %></div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger mt-5 mb-5" role="alert"><%= flash[:alert] %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mt-2">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Home", articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          User
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "Create New", new_article_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "Create New", new_article_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item">
        <% if logged_in? %>
          <%= link_to "Sign Out", session_path(@current_user), method: :delete, class: "btn btn-sm btn-warning font-weight-bold nav-link" %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alphpa Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render "layouts/navbar" %>
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/login.html.erb
<h1> Log in to alpha blog </h1>

<div>
  <%= form_with(model: @user, url: sessions_path, method: :post, local: true) do |f|%>
    <div class="form-group">
      <%= f.label :username, "User name" %>
      <%= f.text_field :username, placeholder: "Enter username", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password, "Password" %>
      <%=f.password_field :password, placeholder: "Enter password", class: "form-control" %>
    </div>
    <%= f.submit "Sign In", class: 'btn btn-primary' %>
  <% end %>
</div>